# Generated by Django 4.1.7 on 2023-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril1', '0002_alter_model1_options_model2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='pole3',
        ),
        migrations.AddField(
            model_name='model2',
            name='pole4',
            field=models.ManyToManyField(to='pril1.model1'),
        ),
    ]
